version: "2.3"

services:

    zookeeper:
        image: zookeeper:3.4.10
        container_name: zookeeper
        hostname: zookeeper
        restart: always
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zookeeper:2888:3888
        volumes:
            - zookeeper_data:/data
            - zookeeper_datalog:/datalog

    kafka:
        image: wurstmeister/kafka:2.12-2.2.1
        container_name: kafka
        hostname: kafka
        depends_on:
            - zookeeper
        restart: always
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_HEAP_OPTS: '-Xmx256M -Xms256M'
            DEFAULT_REPLICATION_FACTOR: 1
            MIN_INSYNC_REPLICAS: 1
            KAFKA_DELETE_TOPIC_ENABLE: "true"
            # KAFKA_LISTENERS: 'kafka'
            # KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
            KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        volumes:
            - kafka_log:/infra/log/kafka/kafka
            - kafka_data:/infra/data/kafka/kafka

    httpsink:
        image: debian:jessie-slim
        container_name: httpsink
        restart: always
        hostname: httpsink
        ports:
            - 12345:12345
        environment:
            PORT: 12345
        volumes:
            - ./infra/httpsink/httpsink:/httpsink
        entrypoint: /httpsink

    namenode:
        image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
        container_name: namenode
        hostname: namenode
        restart: always
        volumes:
            - namenode:/hadoop/dfs/name
        environment:
            - CLUSTER_NAME=test
        env_file:
            - ./infra/hadoop/hadoop.env

    datanode:
        image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
        container_name: datanode
        hostname: datanode
        restart: always
        volumes:
            - datanode:/hadoop/dfs/data
        env_file:
            - ./infra/hadoop/hadoop.env
        environment:
            SERVICE_PRECONDITION: "namenode:50070"

    resourcemanager:
        image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
        container_name: resourcemanager
        hostname: resourcemanager
        restart: always
        environment:
            SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
        env_file:
            - ./infra/hadoop/hadoop.env

    nodemanager:
        image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
        container_name: nodemanager
        hostname: nodemanager
        restart: always
        environment:
            SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
        env_file:
            - ./infra/hadoop/hadoop.env

    historyserver:
        image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
        container_name: historyserver
        hostname: historyserver
        restart: always
        volumes:
            - historyserver:/hadoop/yarn/timeline
        environment:
            SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
        env_file:
            - ./infra/hadoop/hadoop.env

volumes:
    zookeeper_data:
    zookeeper_datalog:
    kafka_data:
    kafka_log:
    datanode:
    namenode:
    historyserver:
