version: "2.3"

services:

    hbase-master:
        image: bde2020/hbase-master:1.0.0-hbase1.2.6
        container_name: hbase-master
        hostname: hbase-master
        restart: always
        env_file:
            - ./infra/hbase/hbase.env
        environment:
            SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181"
        ports:
            - 16010:16010

    hbase-regionserver:
        image: bde2020/hbase-regionserver:1.0.0-hbase1.2.6
        container_name: hbase-regionserver
        hostname: hbase-regionserver
        restart: always
        env_file:
            - ./infra/hbase/hbase.env
        environment:
            HBASE_CONF_hbase_regionserver_hostname: hbase-regionserver
            SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181 hbase-master:16010"
        ports:
            - 16030:16030