version: "2.3"

services:

    hive-server:
        image: bde2020/hive:2.3.2-postgresql-metastore
        container_name: hive-server
        hostname: hive-server
        restart: always
        env_file:
            - ./infra/hive/hive.env
        environment:
            HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
            SERVICE_PRECONDITION: "hive-metastore:9083"
        ports:
            - "10000:10000"
            - "10002:10002"
        volumes:
            - hive:/data

    hive-metastore:
        image: bde2020/hive:2.3.2-postgresql-metastore
        container_name: hive-metastore
        hostname: hive-metastore
        restart: always
        env_file:
            - ./infra/hive/hive.env
        ports:
            - "9083:9083"
        command: /opt/hive/bin/hive --service metastore
        environment:
            SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"

    hive-metastore-postgresql:
        image: bde2020/hive-metastore-postgresql:2.3.0
        container_name: hive-metastore-postgresql
        hostname: hive-metastore-postgresql
        restart: always

volumes:
    hive:
