version: "2.3"

services:

    spark-master:
        image: bde2020/spark-master:2.4.4-hadoop2.7
        container_name: spark-master
        hostname: spark-master
        restart: always
        ports:
            - "8080:8080"
            - "7077:7077"
        environment:
            - INIT_DAEMON_STEP=setup_spark

    spark-worker:
        image: bde2020/spark-worker:2.4.4-hadoop2.7
        container_name: spark-worker
        hostname: spark-worker
        restart: always
        depends_on:
            - spark-master
        ports:
            - "8082:8081"
        environment:
            - "SPARK_MASTER=spark://spark-master:7077"
        volumes:
            - spark_data:/data

volumes:
    spark_data:
